// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZxdPaQ4qXPp410lhWYufIMaXzTQRxZBA',
    appId: '1:649734845897:web:9bc4e5980ddaaef5016418',
    messagingSenderId: '649734845897',
    projectId: 'librarymanagement-1e21c',
    authDomain: 'librarymanagement-1e21c.firebaseapp.com',
    storageBucket: 'librarymanagement-1e21c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn23o-jTznjVnq1SacF6i2wzzwGu_cNPw',
    appId: '1:649734845897:android:c860d5f1c5017567016418',
    messagingSenderId: '649734845897',
    projectId: 'librarymanagement-1e21c',
    storageBucket: 'librarymanagement-1e21c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh2hULkmWFGtyWdHV4067uIjQeqz4eyws',
    appId: '1:649734845897:ios:80be7e2289f4d181016418',
    messagingSenderId: '649734845897',
    projectId: 'librarymanagement-1e21c',
    storageBucket: 'librarymanagement-1e21c.firebasestorage.app',
    iosClientId: '649734845897-h9huq7bn3gcf9rdah6as2elj3o2bmtkn.apps.googleusercontent.com',
    iosBundleId: 'com.example.libraryManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh2hULkmWFGtyWdHV4067uIjQeqz4eyws',
    appId: '1:649734845897:ios:80be7e2289f4d181016418',
    messagingSenderId: '649734845897',
    projectId: 'librarymanagement-1e21c',
    storageBucket: 'librarymanagement-1e21c.firebasestorage.app',
    iosClientId: '649734845897-h9huq7bn3gcf9rdah6as2elj3o2bmtkn.apps.googleusercontent.com',
    iosBundleId: 'com.example.libraryManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZxdPaQ4qXPp410lhWYufIMaXzTQRxZBA',
    appId: '1:649734845897:web:bff3921379d6a266016418',
    messagingSenderId: '649734845897',
    projectId: 'librarymanagement-1e21c',
    authDomain: 'librarymanagement-1e21c.firebaseapp.com',
    storageBucket: 'librarymanagement-1e21c.firebasestorage.app',
  );
}
